
import java.awt.Component;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hayou1838
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        if(redirect.speedBump == 1){
            this.setVisible(false);
            new Frame3().setVisible(true);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        f2Activate = new javax.swing.JButton();
        liquidity = new javax.swing.JLabel();
        profitability = new javax.swing.JLabel();
        solvency = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        liqInput = new javax.swing.JTextField();
        proInput = new javax.swing.JTextField();
        solInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        toF1fromF2 = new javax.swing.JMenuItem();
        toF3fromF3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 350));

        Background.setBackground(new java.awt.Color(204, 204, 255));
        Background.setLayout(null);

        title.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        title.setText("The functioning O_O");
        Background.add(title);
        title.setBounds(0, 0, 600, 70);

        f2Activate.setText("OK");
        f2Activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActivateActionPerformed(evt);
            }
        });
        Background.add(f2Activate);
        f2Activate.setBounds(270, 240, 47, 30);

        liquidity.setText("Liquidity");
        Background.add(liquidity);
        liquidity.setBounds(10, 70, 70, 30);

        profitability.setText("Profitability");
        Background.add(profitability);
        profitability.setBounds(10, 110, 70, 30);

        solvency.setText("Solvency");
        Background.add(solvency);
        solvency.setBounds(10, 150, 70, 30);

        name.setText("Company Name");
        Background.add(name);
        name.setBounds(10, 200, 80, 14);

        liqInput.setText("jTextField1");
        Background.add(liqInput);
        liqInput.setBounds(90, 70, 500, 30);

        proInput.setText("jTextField2");
        Background.add(proInput);
        proInput.setBounds(90, 110, 500, 30);

        solInput.setText("jTextField3");
        Background.add(solInput);
        solInput.setBounds(90, 150, 500, 30);

        nameInput.setText("jTextField4");
        Background.add(nameInput);
        nameInput.setBounds(90, 190, 500, 30);

        jMenu1.setText("Go to");

        toF1fromF2.setText("Frame 1");
        toF1fromF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toF1fromF2ActionPerformed(evt);
            }
        });
        jMenu1.add(toF1fromF2);

        toF3fromF3.setText("Frame 3");
        toF3fromF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toF3fromF3ActionPerformed(evt);
            }
        });
        jMenu1.add(toF3fromF3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f2ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActivateActionPerformed
      new redirect().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_f2ActivateActionPerformed
    private void toF1fromF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toF1fromF2ActionPerformed
        this.setVisible(false);
        new Frame1().setVisible(true);
    }//GEN-LAST:event_toF1fromF2ActionPerformed

    private void toF3fromF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toF3fromF3ActionPerformed
        this.setVisible(false);
        new Frame3().setVisible(true);
    }//GEN-LAST:event_toF3fromF3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton f2Activate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField liqInput;
    private javax.swing.JLabel liquidity;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField proInput;
    private javax.swing.JLabel profitability;
    private javax.swing.JTextField solInput;
    private javax.swing.JLabel solvency;
    private javax.swing.JLabel title;
    private javax.swing.JMenuItem toF1fromF2;
    private javax.swing.JMenuItem toF3fromF3;
    // End of variables declaration//GEN-END:variables

    private void setLabel(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
