
import java.awt.Component;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hayou1838
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        if(redirect.speedBump == 1){
            this.setVisible(false);
            new Frame3().setVisible(true);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        f2Activate = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        companyName = new javax.swing.JTextField();
        profitability1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        gpmText5 = new javax.swing.JLabel();
        grossProfit12 = new javax.swing.JTextField();
        netSales7 = new javax.swing.JTextField();
        fractionbar9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        gpmText2 = new javax.swing.JLabel();
        grossProfit3 = new javax.swing.JTextField();
        netSales2 = new javax.swing.JTextField();
        fractionbar2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        gpmText9 = new javax.swing.JLabel();
        grossProfit13 = new javax.swing.JTextField();
        netSales8 = new javax.swing.JTextField();
        fractionbar10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        gpmText10 = new javax.swing.JLabel();
        grossProfit14 = new javax.swing.JTextField();
        netSales9 = new javax.swing.JTextField();
        fractionbar11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        gpmText11 = new javax.swing.JLabel();
        grossProfit15 = new javax.swing.JTextField();
        netSales10 = new javax.swing.JTextField();
        fractionbar12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gpmText4 = new javax.swing.JLabel();
        grossProfit8 = new javax.swing.JTextField();
        netSales3 = new javax.swing.JTextField();
        fractionbar5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gpmText1 = new javax.swing.JLabel();
        grossProfit2 = new javax.swing.JTextField();
        netSales1 = new javax.swing.JTextField();
        fractionbar1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        gpmText8 = new javax.swing.JLabel();
        grossProfit11 = new javax.swing.JTextField();
        netSales6 = new javax.swing.JTextField();
        fractionbar8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        gpmText7 = new javax.swing.JLabel();
        grossProfit10 = new javax.swing.JTextField();
        netSales5 = new javax.swing.JTextField();
        fractionbar7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        gpmText6 = new javax.swing.JLabel();
        grossProfit9 = new javax.swing.JTextField();
        netSales4 = new javax.swing.JTextField();
        fractionbar6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        gpmText12 = new javax.swing.JLabel();
        grossProfit16 = new javax.swing.JTextField();
        netSales11 = new javax.swing.JTextField();
        fractionbar13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        gpmText13 = new javax.swing.JLabel();
        grossProfit17 = new javax.swing.JTextField();
        netSales12 = new javax.swing.JTextField();
        fractionbar14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        toF1fromF2 = new javax.swing.JMenuItem();
        toF3fromF3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(204, 204, 255));
        Background.setLayout(null);

        title.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Please insert company infromation");
        Background.add(title);
        title.setBounds(0, 0, 630, 70);

        f2Activate.setText("OK");
        f2Activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActivateActionPerformed(evt);
            }
        });
        Background.add(f2Activate);
        f2Activate.setBounds(530, 60, 100, 30);

        name.setText("Company Name:");
        Background.add(name);
        name.setBounds(20, 70, 130, 14);

        companyName.setText("Facebook");
        companyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameActionPerformed(evt);
            }
        });
        Background.add(companyName);
        companyName.setBounds(120, 60, 400, 30);

        profitability1.setText("Profitability Ratios:");
        Background.add(profitability1);
        profitability1.setBounds(10, 100, 110, 30);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText5.setText("Profit Margin:");
        jPanel8.add(gpmText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit12.setText("Net Income");
        grossProfit12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit12ActionPerformed(evt);
            }
        });
        jPanel8.add(grossProfit12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 120, 30));

        netSales7.setText("Net Sales");
        netSales7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales7ActionPerformed(evt);
            }
        });
        jPanel8.add(netSales7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, 30));

        fractionbar9.setText("____________________");
        jPanel8.add(fractionbar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, 20));

        Background.add(jPanel8);
        jPanel8.setBounds(0, 140, 270, 90);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText2.setText("Gross Profit Margin:");
        jPanel9.add(gpmText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit3.setText("Gross Profit");
        grossProfit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit3ActionPerformed(evt);
            }
        });
        jPanel9.add(grossProfit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        netSales2.setText("Net Sales");
        netSales2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales2ActionPerformed(evt);
            }
        });
        jPanel9.add(netSales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, 30));

        fractionbar2.setText("____________________");
        jPanel9.add(fractionbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 120, 20));

        Background.add(jPanel9);
        jPanel9.setBounds(0, 230, 270, 90);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText9.setText("Asset Turnover:");
        jPanel10.add(gpmText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit13.setText("Net Sales");
        grossProfit13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit13ActionPerformed(evt);
            }
        });
        jPanel10.add(grossProfit13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 120, 30));

        netSales8.setText("Average Total Assets");
        netSales8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales8ActionPerformed(evt);
            }
        });
        jPanel10.add(netSales8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, 30));

        fractionbar10.setText("____________________");
        jPanel10.add(fractionbar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, 20));

        Background.add(jPanel10);
        jPanel10.setBounds(0, 320, 270, 90);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText10.setText("Return on Assets:");
        jPanel11.add(gpmText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit14.setText("Net Income");
        grossProfit14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit14ActionPerformed(evt);
            }
        });
        jPanel11.add(grossProfit14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 30));

        netSales9.setText("Average Total Assets");
        netSales9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales9ActionPerformed(evt);
            }
        });
        jPanel11.add(netSales9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, 30));

        fractionbar11.setText("____________________");
        jPanel11.add(fractionbar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 20));

        Background.add(jPanel11);
        jPanel11.setBounds(0, 410, 270, 90);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText11.setText("Return on Equity:");
        jPanel12.add(gpmText11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit15.setText("Net Income");
        grossProfit15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit15ActionPerformed(evt);
            }
        });
        jPanel12.add(grossProfit15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 30));

        netSales10.setText("Avg Shareholder's Eqt");
        netSales10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales10ActionPerformed(evt);
            }
        });
        jPanel12.add(netSales10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, 30));

        fractionbar12.setText("____________________");
        jPanel12.add(fractionbar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, 20));

        Background.add(jPanel12);
        jPanel12.setBounds(0, 500, 270, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText4.setText("Working Capital:");
        jPanel2.add(gpmText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        grossProfit8.setText("Current Assets");
        grossProfit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit8ActionPerformed(evt);
            }
        });
        jPanel2.add(grossProfit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 30));

        netSales3.setText("Current Liabilities");
        netSales3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales3ActionPerformed(evt);
            }
        });
        jPanel2.add(netSales3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, 30));

        fractionbar5.setText("____________________");
        jPanel2.add(fractionbar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 130, 20));

        Background.add(jPanel2);
        jPanel2.setBounds(360, 140, 270, 90);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText1.setText("Current Ratio:");
        jPanel1.add(gpmText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit2.setText("Current Assets");
        grossProfit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit2ActionPerformed(evt);
            }
        });
        jPanel1.add(grossProfit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 120, 30));

        netSales1.setText("Current Liabilities");
        netSales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales1ActionPerformed(evt);
            }
        });
        jPanel1.add(netSales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, 30));

        fractionbar1.setText("____________________");
        jPanel1.add(fractionbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, 20));

        Background.add(jPanel1);
        jPanel1.setBounds(360, 230, 270, 90);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText8.setText("Inventory Turnover:");
        jPanel6.add(gpmText8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit11.setText("Cost of Goods Sold");
        grossProfit11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit11ActionPerformed(evt);
            }
        });
        jPanel6.add(grossProfit11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        netSales6.setText("Average inventory");
        netSales6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales6ActionPerformed(evt);
            }
        });
        jPanel6.add(netSales6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, 30));

        fractionbar8.setText("____________________");
        jPanel6.add(fractionbar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 20));

        Background.add(jPanel6);
        jPanel6.setBounds(360, 320, 270, 90);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText7.setText("Receivables Turnover:");
        jPanel5.add(gpmText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit10.setText("Net Credit Sales");
        grossProfit10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit10ActionPerformed(evt);
            }
        });
        jPanel5.add(grossProfit10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 30));

        netSales5.setText("Avg Gross receivables");
        netSales5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales5ActionPerformed(evt);
            }
        });
        jPanel5.add(netSales5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 120, 30));

        fractionbar7.setText("____________________");
        jPanel5.add(fractionbar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, 20));

        Background.add(jPanel5);
        jPanel5.setBounds(360, 410, 270, 90);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText6.setText("Debt Total Assets:");
        jPanel4.add(gpmText6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit9.setText("Total Liabilities");
        grossProfit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit9ActionPerformed(evt);
            }
        });
        jPanel4.add(grossProfit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        netSales4.setText("Total Assets");
        netSales4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales4ActionPerformed(evt);
            }
        });
        jPanel4.add(netSales4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, 30));

        fractionbar6.setText("____________________");
        jPanel4.add(fractionbar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 20));

        Background.add(jPanel4);
        jPanel4.setBounds(360, 500, 270, 90);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText12.setText("Price-Earnings Ratio:");
        jPanel7.add(gpmText12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit16.setText("Market Price per share");
        grossProfit16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit16ActionPerformed(evt);
            }
        });
        jPanel7.add(grossProfit16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        netSales11.setText("Earnings Per Share");
        netSales11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales11ActionPerformed(evt);
            }
        });
        jPanel7.add(netSales11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, 30));

        fractionbar13.setText("____________________");
        jPanel7.add(fractionbar13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 20));

        Background.add(jPanel7);
        jPanel7.setBounds(0, 590, 270, 90);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gpmText13.setText("Payout Ratio:");
        jPanel13.add(gpmText13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        grossProfit17.setText("Cash Dividends");
        grossProfit17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossProfit17ActionPerformed(evt);
            }
        });
        jPanel13.add(grossProfit17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 120, 30));

        netSales12.setText("Net Income");
        netSales12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netSales12ActionPerformed(evt);
            }
        });
        jPanel13.add(netSales12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, 30));

        fractionbar14.setText("____________________");
        jPanel13.add(fractionbar14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 140, 20));

        Background.add(jPanel13);
        jPanel13.setBounds(360, 590, 270, 90);

        jMenu1.setText("Go to");

        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        toF1fromF2.setText("Frame 1");
        toF1fromF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toF1fromF2ActionPerformed(evt);
            }
        });
        jMenu1.add(toF1fromF2);

        toF3fromF3.setText("Frame 3");
        toF3fromF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toF3fromF3ActionPerformed(evt);
            }
        });
        jMenu1.add(toF3fromF3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toF1fromF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toF1fromF2ActionPerformed
        this.setVisible(false);
        new Frame1().setVisible(true);
    }//GEN-LAST:event_toF1fromF2ActionPerformed

    private void toF3fromF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toF3fromF3ActionPerformed
        this.setVisible(false);
        new Frame3().setVisible(true);
    }//GEN-LAST:event_toF3fromF3ActionPerformed

    private void netSales6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales6ActionPerformed

    private void grossProfit11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit11ActionPerformed

    private void netSales5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales5ActionPerformed

    private void grossProfit10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit10ActionPerformed

    private void netSales4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales4ActionPerformed

    private void grossProfit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit9ActionPerformed

    private void netSales3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales3ActionPerformed

    private void grossProfit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit8ActionPerformed

    private void netSales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales1ActionPerformed

    private void grossProfit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit2ActionPerformed

    private void companyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameActionPerformed
            companyName.setToolTipText("Insert the name of the company you want to calculate");
    }//GEN-LAST:event_companyNameActionPerformed

    private void f2ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActivateActionPerformed
        new redirect().setVisible(true);
        this.setVisible(false);
        f2Activate.setToolTipText("make sure you check all the ratios! You don't want to remove this after all your hard work!");
    }//GEN-LAST:event_f2ActivateActionPerformed

    private void netSales10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales10ActionPerformed

    private void grossProfit15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit15ActionPerformed

    private void netSales9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales9ActionPerformed

    private void grossProfit14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit14ActionPerformed

    private void netSales8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales8ActionPerformed

    private void grossProfit13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit13ActionPerformed

    private void netSales2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales2ActionPerformed

    private void grossProfit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit3ActionPerformed

    private void netSales7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales7ActionPerformed

    private void grossProfit12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit12ActionPerformed
        
    }//GEN-LAST:event_grossProfit12ActionPerformed

    private void grossProfit16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit16ActionPerformed

    private void netSales11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales11ActionPerformed

    private void grossProfit17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossProfit17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossProfit17ActionPerformed

    private void netSales12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netSales12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netSales12ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        new HelpFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JTextField companyName;
    private javax.swing.JButton f2Activate;
    private javax.swing.JLabel fractionbar1;
    private javax.swing.JLabel fractionbar10;
    private javax.swing.JLabel fractionbar11;
    private javax.swing.JLabel fractionbar12;
    private javax.swing.JLabel fractionbar13;
    private javax.swing.JLabel fractionbar14;
    private javax.swing.JLabel fractionbar2;
    private javax.swing.JLabel fractionbar5;
    private javax.swing.JLabel fractionbar6;
    private javax.swing.JLabel fractionbar7;
    private javax.swing.JLabel fractionbar8;
    private javax.swing.JLabel fractionbar9;
    private javax.swing.JLabel gpmText1;
    private javax.swing.JLabel gpmText10;
    private javax.swing.JLabel gpmText11;
    private javax.swing.JLabel gpmText12;
    private javax.swing.JLabel gpmText13;
    private javax.swing.JLabel gpmText2;
    private javax.swing.JLabel gpmText4;
    private javax.swing.JLabel gpmText5;
    private javax.swing.JLabel gpmText6;
    private javax.swing.JLabel gpmText7;
    private javax.swing.JLabel gpmText8;
    private javax.swing.JLabel gpmText9;
    private javax.swing.JTextField grossProfit10;
    private javax.swing.JTextField grossProfit11;
    private javax.swing.JTextField grossProfit12;
    private javax.swing.JTextField grossProfit13;
    private javax.swing.JTextField grossProfit14;
    private javax.swing.JTextField grossProfit15;
    private javax.swing.JTextField grossProfit16;
    private javax.swing.JTextField grossProfit17;
    private javax.swing.JTextField grossProfit2;
    private javax.swing.JTextField grossProfit3;
    private javax.swing.JTextField grossProfit8;
    private javax.swing.JTextField grossProfit9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel name;
    private javax.swing.JTextField netSales1;
    private javax.swing.JTextField netSales10;
    private javax.swing.JTextField netSales11;
    private javax.swing.JTextField netSales12;
    private javax.swing.JTextField netSales2;
    private javax.swing.JTextField netSales3;
    private javax.swing.JTextField netSales4;
    private javax.swing.JTextField netSales5;
    private javax.swing.JTextField netSales6;
    private javax.swing.JTextField netSales7;
    private javax.swing.JTextField netSales8;
    private javax.swing.JTextField netSales9;
    private javax.swing.JLabel profitability1;
    private javax.swing.JLabel title;
    private javax.swing.JMenuItem toF1fromF2;
    private javax.swing.JMenuItem toF3fromF3;
    // End of variables declaration//GEN-END:variables

    private void setLabel(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
