/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hayou1838
 */
public class Introduction extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    
    public Introduction() {
        initComponents();
        spreadsheetInput.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nextFrame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spreadsheetInput = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        toF3fromF1 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(null);

        Background.setBackground(new java.awt.Color(204, 255, 255));
        Background.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 30)); // NOI18N
        jLabel1.setText("Financial Health CALCULATOR");
        Background.add(jLabel1);
        jLabel1.setBounds(20, 20, 560, 70);

        nextFrame.setText("User Input");
        nextFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFrameActionPerformed(evt);
            }
        });
        Background.add(nextFrame);
        nextFrame.setBounds(20, 80, 170, 23);

        jLabel2.setText("<html><style> c {font-size: 20px;}</style><div><b>An <c>important</c> tool for the <c>everyday accountant!</c> That could be <c>you!</c> The three things you'd <c>HATE</c> to memorize, are now <c>EASILY</c> accessible with the touch of a <c>button!</c> Sate your hunger of <c>Solvency!</c> Pilfur in <c>Profitability!</c> And laze in the <c>Liquidity!</c></b></div></html>");
        Background.add(jLabel2);
        jLabel2.setBounds(10, 110, 580, 190);

        spreadsheetInput.setText("Spreadsheet Input");
        spreadsheetInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spreadsheetInputActionPerformed(evt);
            }
        });
        Background.add(spreadsheetInput);
        spreadsheetInput.setBounds(380, 80, 190, 23);

        getContentPane().add(Background);
        Background.setBounds(0, -20, 600, 300);

        jMenu1.setText("Go to");

        jMenuItem4.setText("Help");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("UserInput");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        toF3fromF1.setText("Leaderboard");
        toF3fromF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toF3fromF1ActionPerformed(evt);
            }
        });
        jMenu1.add(toF3fromF1);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Teacher");

        jMenuItem2.setText("Sign in");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Sign out");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFrameActionPerformed
        this.setVisible(false);
        new CompanyInput().setVisible(true);
    }//GEN-LAST:event_nextFrameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void toF3fromF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toF3fromF1ActionPerformed
        this.setVisible(false);
        new Leaderboard().setVisible(true);
    }//GEN-LAST:event_toF3fromF1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        new CompanyInput().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.setVisible(false);
        new HelpFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void spreadsheetInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spreadsheetInputActionPerformed
        this.setVisible(false);
        new Frame4().setVisible(true);
    }//GEN-LAST:event_spreadsheetInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Introduction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton nextFrame;
    private javax.swing.JButton spreadsheetInput;
    private javax.swing.JMenuItem toF3fromF1;
    // End of variables declaration//GEN-END:variables
}
