
import java.awt.FlowLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hayou1838
 */
public class redirect extends javax.swing.JFrame {

    /**
     * Creates new form redirect
     */
    public static int speedBump = 0;
    public redirect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setText("Yes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 100, 60, 23);

        jButton2.setText("No");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 100, 60, 23);

        jLabel1.setText("Are you sure this is what you'd like to input?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 220, 70);

        jMenu1.setText("Help");

        jMenuItem1.setText("Click here for an FAQ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         companyOrganizer.ratios[0] = Calculations.profMarg(companyOrganizer.netIncome,companyOrganizer.netSales);
         companyOrganizer.ratios[1] = Calculations.grosProfMarg(companyOrganizer.grossProfit,companyOrganizer.netSales);
         companyOrganizer.ratios[2] = Calculations.assetTrnOvr(companyOrganizer.netSales,companyOrganizer.avgTotalAssets);
         companyOrganizer.ratios[3] = Calculations.rtrnOnAssets(companyOrganizer.netIncome,companyOrganizer.avgTotalAssets);
         companyOrganizer.ratios[4] = Calculations.rtrnOnEquity(companyOrganizer.netIncome,companyOrganizer.avgShareEqt);
         companyOrganizer.ratios[5] = Calculations.prceErngRATIO(companyOrganizer.marketSharePrice,companyOrganizer.eps);
         companyOrganizer.ratios[6] = Calculations.payoutRATIO(companyOrganizer.dividends,companyOrganizer.netIncome);
         //Above are all profit ratios
         companyOrganizer.ratios[7] = Calculations.wrkngCap(companyOrganizer.currentAssets,companyOrganizer.currentLiab);
         companyOrganizer.ratios[8] = Calculations.crrtRATIO(companyOrganizer.currentAssets,companyOrganizer.currentLiab);
         companyOrganizer.ratios[9] = Calculations.invTrnvr(companyOrganizer.cogs,companyOrganizer.avgInv);
         companyOrganizer.ratios[10] = Calculations.recvableTrnvr(companyOrganizer.creditSales,companyOrganizer.totalAssets);
         //Above are all liquidity ratios
         companyOrganizer.ratios[11] = Calculations.debtTtlAssets(companyOrganizer.totalLiab,companyOrganizer.totalAssets);
         //Above is a solvency ratio
         double[] temp = new double[12];
         for (int i = 0; i < temp.length; i++) {
           temp[i] = companyOrganizer.ratios[i];
        }
         
         
         while(temp[0]>=0.5){
             temp[0]/=10;
         }
         temp[0]+=0.2;
         //gives weight to the profit margin for a maximum of 0.5 in profitability
         while(temp[1]>=1){
             temp[0]/=10;
         }
         temp[1]+=0.3;
         //gives weight to the profit margin for a maximum of 1 in profitability
         while(temp[3]>=0.5){
             temp[3]/=4;
         }
         temp[3]+=0.2;
         //gives weight to returns on assets up to a maximum of 0.5 in profitability
         while(temp[4]>=1.5){
             temp[4]/=5;
         }
         temp[4]+=0.4;
         //gives weight to returns on equity up to a maximum of 1.5 in profitability
         if(temp[5]>=40){
             temp[5] = 1;
         }
         //if the price earnings ratio is above 40 times earnings then add 1 in profitability
         while(temp[6]>=1.5){
             temp[6]/=5;
         }
         temp[6]+= 0.3;
         //gives weight to the payout ratio up to a maximum of 1.5 in profitability
         companyOrganizer.profitabilityScore = temp[0]+temp[1]+temp[3]+temp[4]+temp[5]+temp[6];
         //Note: the weights are arbirtaty in nature and are for the fun of a leaderboard
         if(companyOrganizer.profitabilityScore>5){
             companyOrganizer.profitabilityScore = 5;
         }
         //companyOrganizer.profitability.add(companyOrganizer.profitabilityScore);
         if(temp[7]>0){
             temp[7]=1.5;
         }
         //adds 1.5 to liquidity score, if the working capital is negative this is a terrible sign
         if(temp[8]>=1){
             temp[7]=1.5;
         }
         while(temp[9]>=1){
             temp[9]/=4;
         }
         temp[9]+=0.2;
         //the premise is the same as before
         while(temp[10]>=1){
             temp[10]/=4;
         }
         temp[10]+=0.2;
         companyOrganizer.liquidityScore = temp[7]+temp[8]+temp[9]+temp[10];
         int tempSolvScore = 5;
         while(temp[11]>0.9){
             tempSolvScore-=0.15;
             temp[11]-=0.1;
         }
         companyOrganizer.solvencyScore = tempSolvScore;
         companyOrganizer.companies.add(new companyOrganizer(companyOrganizer.companyName,companyOrganizer.profitabilityScore,companyOrganizer.liquidityScore,companyOrganizer.solvencyScore));
         
         //jLabel1.setText(String.valueOf(companyOrganizer.profitabilityScore));
         
         
        this.setVisible(false);
    new Leaderboard().setVisible(true);
    
//        final int MAX = 100;
//        final JFrame frame = new JFrame("JProgress Demo");
//        
//        // create progress bar
//        final JProgressBar pb = new JProgressBar();
//            pb.setMinimum(0);
//            pb.setMaximum(MAX);
//            pb.setStringPainted(true);
//            
//        // add progress bar
//        frame.setLayout(new FlowLayout());
//        frame.getContentPane().add(pb);
//        
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setSize(300, 200);
//        frame.setVisible(true);
//        
//           // update progressbar
//        for (int i = 0; i <= MAX; i++) {
//            final int currentValue = i;
//            try {
//                SwingUtilities.invokeLater(new Runnable() {
//                    public void run() {
//                        pb.setValue(currentValue);
//                    }
//                });
//                java.lang.Thread.sleep(100);
//            } catch (InterruptedException e) {
//                JOptionPane.showMessageDialog(frame, e.getMessage());
//            }
//        }
//        speedBump = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new CompanyInput().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        new HelpFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(redirect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(redirect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(redirect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(redirect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new redirect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
